feat: address bar
horuslabsio/seamlessui pull request #21
Opened 2024-10-03 15:33 UTC by Gift-Naomi

Resolves #5 
![Screenshot 2024-10-03 162653](https://github.com/user-attachments/assets/727f1d69-22a4-444e-a984-7eff09c0df3f)
![Screenshot 2024-10-03 162505](https://github.com/user-attachments/assets/33bc9c4e-0257-4425-b566-5546bafe2025)
![Screenshot 2024-10-03 162858](https://github.com/user-attachments/assets/521ecc81-d5db-44f5-a0eb-926c2bba0153)
![Screenshot 2024-10-03 163101](https://github.com/user-attachments/assets/5919585c-ac4c-43a2-9b6a-476d4c7ca48b)

2024-10-03 16:31 UTC, stephanniegb commented
Hey, deployment fails
<img width="1197" alt="Screenshot 2024-10-03 at 5 31 15 PM" src="https://github.com/user-attachments/assets/1b70a483-a5cd-4a8c-b8e7-27d7d82aba24">

2024-10-05 08:06 UTC, stephanniegb requested changes

2024-10-05 08:06 UTC, stephanniegb commented on public/svg/Check.tsx
Use lucide-react for icons as much as possible eg for the copy, close and check

2024-10-05 08:06 UTC, stephanniegb commented on app/components/CopyButton.tsx
Please use a library for copy functionality

2024-10-06 17:39 UTC, stephanniegb commented
<img width="1204" alt="Screenshot 2024-10-06 at 6 39 17 PM" src="https://github.com/user-attachments/assets/c65bdd8c-d870-4b0f-85c8-a9d6d910570b">
Just delete the pnpm file

2024-10-07 07:31 UTC, Oshioke-Salaki commented
lgtm 🚀

2024-10-07 07:31 UTC, merged